'use client';
import { apiFetch } from '../lib/api-fetch';

import {useEffect,useRef,useState} from 'react';
import {LoaderCircle,Download,Save,Upload} from 'lucide-react';

export type Profile={id:string;version:number;updated:string;config:ProfileConfig};
type Basis='unknown'|'included'|'excluded';
type Valuation={sale_basis:Basis;cost_basis:Basis;settlement_basis:Basis;vat_rate:string;note:string};
type ProfileConfig={expected_headers:Record<string,string>;net_source:'mapped'|'cost'|'none';name:string;sheet:string;header_row:number;end_row:number|null;columns:Record<string,string>;customer:string;branch:string;discount_mode:string;valuation:Valuation};
type Inspection={sheets:{name:string;rows:number;columns:number}[];sheet:string;header_row:number;columns:{column:string;label:string}[];sample:string[][]};
type PreviewRow={sku:string;qty:string;price:string;gross:string;source_cost_price:string|null;net:string|null;discount:string;errors:string[]};
type Preview={config:ProfileConfig;rows:number;ready:number;blocked:number;sample:PreviewRow[]};
type HistoryPage<T>={rows:T[];total:number;page:number;size:number;pages:number};
type Pager={total:number;page:number;size:number;pages:number};
const emptyPager:Pager={total:0,page:1,size:20,pages:1};
type ExportEntry={id:string;at:string;batch_id:string;filename:string;rows:number;source_rows:number;scope:string;skipped_rows:number;previous_identical_exports:number;snapshot:{period:string;rows:{sku:string;price:string;qty:string;discount:string}[]}};
type ImportEntry={id:string;at:string;name:string;period:string;batch_id:string;duplicate_override:boolean;error:string|null;source_available:boolean};
type BackupSummary={created:string;batches:number;rows:number;profiles:number;valuations:number;mappings:number;rules:number;imports:number;exports:number;files:number};
const defaultValuation:Valuation={sale_basis:'unknown',cost_basis:'unknown',settlement_basis:'unknown',vat_rate:'7',note:''};
const defaultConfig:ProfileConfig={expected_headers:{},net_source:'mapped',name:'',sheet:'',header_row:1,end_row:null,columns:{},customer:'',branch:'',discount_mode:'auto',valuation:defaultValuation};
const fields:[string,string][]=[['sku','SKU / รหัสสินค้า'],['partner','รหัสสินค้าอ้างอิง'],['barcode','Barcode (อ้างอิงเท่านั้น)'],['qty','จำนวน'],['price','ราคาขายต่อหน่วย'],['gross','ยอดขายรวม'],['cost_price','ต้นทุนต่อหน่วย'],['cost_total','ต้นทุนรวม'],['net','ยอดหลังหัก / ส่งคืนรวม'],['discount','ส่วนลด / GP'],['mg','MG (ข้อมูลประกอบ)'],['customer','ลูกค้า / Shop'],['branch','ชื่อสาขา'],['branch_code','รหัสสาขา'],['date','วันที่ขาย']];
async function api<T>(url:string,options?:RequestInit):Promise<T>{const r=await apiFetch('/api'+url,options);if(!r.ok){const e=await r.json().catch(()=>({detail:'ติดต่อระบบไม่ได้'}));throw new Error(typeof e.detail==='string'?e.detail:JSON.stringify(e.detail));}return r.json();}
const post=(body:unknown):RequestInit=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const num=(n:string|number|null|undefined)=>n==null?'ไม่ระบุ':Number(n).toLocaleString('th-TH',{maximumFractionDigits:2});
const date=(v:string)=>new Date(v).toLocaleString('th-TH');
const download=(name:string)=>{const a=document.createElement('a');a.href='/api/backups/file/'+encodeURIComponent(name);a.download=name;a.click();};

export default function OperationsPanel({batch,profiles,onProfilesChanged,onDataChanged,onRestored}:{batch:{id:string;groups:{customer:string}[]}|null;profiles:Profile[];onProfilesChanged:()=>Promise<void>;onDataChanged:()=>Promise<void>;onRestored:()=>Promise<void>}){
 const [section,setSection]=useState<'formats'|'valuation'|'history'|'backup'>('formats');
 const [busy,setBusy]=useState('');const [message,setMessage]=useState<{error:boolean;text:string}|null>(null);
 const [profileId,setProfileId]=useState('');const [cfg,setCfg]=useState<ProfileConfig>(defaultConfig);const [sampleFile,setSampleFile]=useState<File|null>(null);const [inspection,setInspection]=useState<Inspection|null>(null);const [preview,setPreview]=useState<Preview|null>(null);const [previewSignature,setPreviewSignature]=useState('');
 const [customer,setCustomer]=useState('');const [valuation,setValuation]=useState<Valuation>(defaultValuation);const [applyCurrent,setApplyCurrent]=useState(false);const [savedValuations,setSavedValuations]=useState<{customer:string;settings:Valuation}[]>([]);
 const [imports,setImports]=useState<ImportEntry[]>([]);const [exports,setExports]=useState<ExportEntry[]>([]);const [backups,setBackups]=useState<{name:string;bytes:number}[]>([]);const [backupFile,setBackupFile]=useState<File|null>(null);const [backupPreview,setBackupPreview]=useState<{archive_hash:string;summary:BackupSummary}|null>(null);const [restoreConfirmed,setRestoreConfirmed]=useState(false);const [safetyBackup,setSafetyBackup]=useState('');
 const [importPager,setImportPager]=useState<Pager>(emptyPager);const [exportPager,setExportPager]=useState<Pager>(emptyPager);
 const input=useRef<HTMLInputElement>(null);const backupInput=useRef<HTMLInputElement>(null);
 const run=async(fn:()=>Promise<void>,label:string)=>{setBusy(label);setMessage(null);try{await fn();}catch(e){setMessage({error:true,text:e instanceof Error?e.message:'ไม่สำเร็จ'});}finally{setBusy('');}};
 const clearHistory=()=>{
  if(!window.confirm('ล้างประวัติ Import / Export ทั้งหมดทุกชุดข้อมูลหรือไม่? รายการขาย การตั้งค่า และไฟล์เดิมยังคงอยู่ แต่จะดาวน์โหลดผ่านประวัติที่ล้างไม่ได้ และข้อมูลตรวจซ้ำจากประวัติเดิมจะถูกล้างด้วย'))return;
  run(async()=>{
   const result=await api<{cleared_imports:number;cleared_exports:number}>('/history?confirm=true',{method:'DELETE'});
   setImports([]);setExports([]);setImportPager(v=>({...v,total:0,page:1,pages:1}));setExportPager(v=>({...v,total:0,page:1,pages:1}));
   setMessage({error:false,text:`ล้างประวัติแล้ว: Import ${result.cleared_imports} รายการ / Export ${result.cleared_exports} รายการ · คงรายการขายและไฟล์เดิมไว้`});
  },'กำลังล้างประวัติ…');
 };
 const loadHistory=async(kind:'import'|'export',page:number,size:number)=>{
  if(kind==='import'){
   const result=await api<HistoryPage<ImportEntry>>(`/import-history?page=${page}&size=${size}`);
   setImports(result.rows);setImportPager({total:result.total,page:result.page,size:result.size,pages:result.pages});
  }else{
   const result=await api<HistoryPage<ExportEntry>>(`/export-history?page=${page}&size=${size}`);
   setExports(result.rows);setExportPager({total:result.total,page:result.page,size:result.size,pages:result.pages});
  }
 };
 const changeHistoryPage=(kind:'import'|'export',page:number,size:number)=>run(()=>loadHistory(kind,page,size),'กำลังโหลดประวัติ…');
 const loadSettings=async()=>setSavedValuations(await api('/valuations'));
 useEffect(()=>{if(section==='valuation')run(loadSettings,'กำลังโหลดฐานราคา…');if(section==='history')run(async()=>{const results=await Promise.allSettled([loadHistory('import',importPager.page,importPager.size),loadHistory('export',exportPager.page,exportPager.size)]);const failed=results.find(r=>r.status==='rejected');if(failed?.status==='rejected')throw failed.reason;},'กำลังโหลดประวัติ…');if(section==='backup')run(async()=>setBackups(await api('/backups')),'กำลังโหลดรายการสำรอง…');},[section]); // User-triggered section loading.
 const inspect=()=>run(async()=>{if(!sampleFile)throw new Error('เลือก Excel ตัวอย่างก่อน');const body=new FormData();body.append('file',sampleFile);body.append('sheet',cfg.sheet);body.append('header_row',String(cfg.header_row));const result=await api<Inspection>('/profiles/inspect',{method:'POST',body});setInspection(result);setCfg(v=>({...v,sheet:result.sheet}));setPreview(null);},'กำลังอ่านชีตและคอลัมน์…');
 const previewProfile=()=>run(async()=>{if(!sampleFile)throw new Error('เลือก Excel ตัวอย่างก่อน');const body=new FormData();body.append('file',sampleFile);body.append('config',JSON.stringify(cfg));const result=await api<Preview>('/profiles/preview',{method:'POST',body});setPreview(result);setCfg(result.config);setPreviewSignature(JSON.stringify(result.config));},'กำลังทดสอบ Mapping และยอด…');
 const saveProfile=()=>run(async()=>{const saved=await api<Profile>('/profiles',post({id:profileId||undefined,config:cfg}));setProfileId(saved.id);await onProfilesChanged();setMessage({error:false,text:`บันทึกรูปแบบ ${saved.config.name} เวอร์ชัน ${saved.version} แล้ว เลือกใช้ได้ในส่วน Import`});},'กำลังบันทึกรูปแบบ…');
 const selectProfile=(id:string)=>{setProfileId(id);setCfg(id?{...defaultConfig,...profiles.find(p=>p.id===id)!.config}:{...defaultConfig,columns:{}});setPreview(null);setInspection(null);};
 const saveValuation=()=>run(async()=>{const result=await api<{updated:number}>('/valuations',post({customer,settings:valuation,batch_id:applyCurrent?batch?.id:undefined}));await loadSettings();if(applyCurrent)await onDataChanged();setMessage({error:false,text:`บันทึกฐานราคา ${customer} แล้ว${applyCurrent?` · ปรับใช้ ${result.updated} รายการในชุดนี้`:' · ใช้กับการนำเข้าครั้งถัดไป'}`});},'กำลังบันทึกฐานราคา…');
 const checkBackup=(file:File)=>{setBackupFile(file);setBackupPreview(null);setRestoreConfirmed(false);run(async()=>{const body=new FormData();body.append('file',file);setBackupPreview(await api('/backups/preview',{method:'POST',body}));},'กำลังตรวจโครงสร้างและ Checksum ไฟล์สำรอง…');};
 const restore=()=>{if(!backupPreview||!backupFile||!restoreConfirmed)return;if(!window.confirm(`แทนที่ข้อมูลทั้งหมดด้วยชุดสำรอง ${backupPreview.summary.batches} ชุด / ${backupPreview.summary.rows} รายการ? ระบบจะสำรองข้อมูลปัจจุบันไว้ก่อน`))return;run(async()=>{const body=new FormData();body.append('file',backupFile);body.append('archive_hash',backupPreview.archive_hash);body.append('confirm','true');const result=await api<{safety_backup:string}>('/backups/restore',{method:'POST',body});setSafetyBackup(result.safety_backup);setBackupPreview(null);setRestoreConfirmed(false);await onRestored();setBackups(await api('/backups'));setMessage({error:false,text:'กู้คืนข้อมูลสำเร็จ พร้อมไฟล์สำรองก่อนกู้คืนด้านล่าง'});},'กำลังกู้คืนข้อมูล กรุณารอสักครู่…');};
 return <div className="operations-panel"><div className="operations-nav">{([['formats','รูปแบบนำเข้า'],['valuation','ฐานราคา / VAT'],['history','ประวัติ Import / Export'],['backup','สำรอง / กู้คืน']] as const).map(([key,label])=><button key={key} className={section===key?'selected':''} disabled={!!busy} onClick={()=>{setSection(key);setMessage(null);}}>{label}</button>)}</div>
 {busy&&<div className="busy" role="status"><LoaderCircle className="spin" size={18}/>{busy}</div>}{message&&<div className={`notice ${message.error?'error':'success'}`} role={message.error?'alert':'status'}>{message.text}</div>}
 <fieldset disabled={!!busy}>
 {section==='formats'&&<section><h3>ตั้งค่ารูปแบบ Excel แบบตาราง</h3><p className="ops-note">เลือกชีตและแถวหัวตาราง จับคู่คอลัมน์ แล้วดูตัวอย่างก่อนบันทึก · PDF ใช้ตัวอ่านรูปแบบเดิม · ค่าฐานราคาของลูกค้าที่ตั้งไว้จะใช้ก่อนค่ารูปแบบ</p>
 <div className="ops-grid"><label>รูปแบบที่บันทึก<select aria-label="แก้รูปแบบนำเข้า" value={profileId} onChange={e=>selectProfile(e.target.value)}><option value="">สร้างรูปแบบใหม่</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.config.name} · v{p.version}</option>)}</select></label><label>ชื่อรูปแบบ<input aria-label="ชื่อรูปแบบนำเข้า" value={cfg.name} onChange={e=>setCfg({...cfg,name:e.target.value})}/></label></div>
 <input hidden ref={input} type="file" accept=".xlsx" aria-label="ไฟล์ตัวอย่างรูปแบบใหม่" onChange={e=>{setSampleFile(e.target.files?.[0]||null);setInspection(null);setPreview(null);setCfg(v=>({...v,sheet:''}));}}/>
 <div className="ops-actions"><button className="button secondary" onClick={()=>input.current?.click()}><Upload size={16}/> เลือก Excel ตัวอย่าง</button><span>{sampleFile?.name||'ยังไม่เลือกไฟล์'}</span></div>
 <div className="ops-grid"><label>ชีต<select aria-label="ชีตรูปแบบใหม่" value={cfg.sheet} onChange={e=>{setCfg({...cfg,sheet:e.target.value});setPreview(null);}}><option value="">ชีตแรก</option>{inspection?.sheets.map(s=><option key={s.name} value={s.name}>{s.name} ({s.rows} แถว)</option>)}{!inspection&&cfg.sheet&&<option value={cfg.sheet}>{cfg.sheet}</option>}</select></label><label>แถวหัวตาราง<input aria-label="แถวหัวตาราง" type="number" min={1} max={1000} value={cfg.header_row} onChange={e=>setCfg({...cfg,header_row:Number(e.target.value)})}/></label><label>แถวข้อมูลสุดท้าย (เว้นว่าง = จบชีต)<input aria-label="แถวข้อมูลสุดท้าย" type="number" value={cfg.end_row??''} onChange={e=>setCfg({...cfg,end_row:e.target.value?Number(e.target.value):null})}/></label></div>
 <button className="button secondary" disabled={!sampleFile} onClick={inspect}>อ่านชีตและหัวตาราง</button>
 {inspection&&<><p className="ops-note">ตัวอย่างต้นทาง 5 แถวแรก · แสดงสูงสุด 12 คอลัมน์ (เลือก Mapping ได้ทุกคอลัมน์)</p><div className="table-scroll"><table><thead><tr>{inspection.columns.slice(0,12).map(c=><th key={c.column}>{c.column}: {c.label}</th>)}</tr></thead><tbody>{inspection.sample.map((line,i)=><tr key={i}>{line.slice(0,12).map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div></>}
 <div className="ops-grid mapping-fields">{fields.map(([key,label])=><label key={key}>{label}<select aria-label={`คอลัมน์ ${key}`} value={cfg.columns[key]||''} onChange={e=>setCfg({...cfg,columns:{...cfg.columns,[key]:e.target.value}})}><option value="">ไม่ระบุ</option>{inspection?.columns.map(c=><option key={c.column} value={c.column}>{c.column}: {c.label||'(ไม่มีหัวข้อ)'}</option>)}{!inspection&&cfg.columns[key]&&<option value={cfg.columns[key]}>{cfg.columns[key]}</option>}</select></label>)}</div>
 <div className="ops-grid"><label>ลูกค้าเริ่มต้น (เมื่อไม่เลือกคอลัมน์)<input aria-label="ลูกค้ารูปแบบใหม่" value={cfg.customer} onChange={e=>setCfg({...cfg,customer:e.target.value})}/></label><label>สาขาเริ่มต้น<input aria-label="สาขารูปแบบใหม่" value={cfg.branch} onChange={e=>setCfg({...cfg,branch:e.target.value})}/></label><label>รูปแบบส่วนลด<select aria-label="ชนิดส่วนลดรูปแบบใหม่" value={cfg.discount_mode} onChange={e=>setCfg({...cfg,discount_mode:e.target.value})}><option value="auto">ตรวจจากยอดอัตโนมัติ</option><option value="percent">เปอร์เซ็นต์ เช่น 25 หรือ 25%</option><option value="fraction">อัตราส่วน เช่น 0.25 = 25%</option><option value="amount">ส่วนลดเป็นเงินรวมรายแถว</option></select></label></div>
 <label>แหล่งยอดสุทธิ / ยอดส่งคืน<select aria-label="แหล่งยอดสุทธิรูปแบบใหม่" value={cfg.net_source} onChange={e=>setCfg({...cfg,net_source:e.target.value as ProfileConfig['net_source']})}><option value="mapped">ใช้คอลัมน์ยอดสุทธิที่ Mapping (ไม่ใช้ต้นทุนแทน)</option><option value="cost">ยืนยันว่าต้นทุนในไฟล์นี้คือยอดส่งคืน</option><option value="none">ไม่มีฐานยอดสุทธิ ใช้ส่วนลดที่ระบุหรือเริ่ม 0%</option></select></label>
 <p className="ops-note">หัวคอลัมน์จะถูกบันทึกจากตัวอย่าง หากไฟล์ครั้งถัดไปเปลี่ยน ระบบจะให้ตรวจ Mapping ใหม่ก่อนนำเข้า · Profile เดิมที่ยังไม่มีหัวอ้างอิงต้องดูตัวอย่างและบันทึกใหม่</p>
 <p className="ops-note">ต้องมี SKU/รหัสอ้างอิง, จำนวน และราคาขายต่อหน่วยหรือยอดขายรวม · ใช้ต้นทุนเป็นยอดส่งคืนเฉพาะเมื่อเลือกยืนยันด้านบน หากไม่มีส่วนลด/ฐานสุทธิให้เริ่มที่ 0% และแก้ภายหลังได้ · MG เป็นข้อมูลประกอบ · แถวรวมท้ายตารางต้องกำหนดแถวสุดท้ายให้สิ้นสุดก่อนแถวนั้น</p>
 <div className="ops-actions"><button className="button secondary" disabled={!sampleFile||!cfg.sheet} onClick={previewProfile}>ดูตัวอย่าง Mapping</button><button className="button primary" disabled={!preview||previewSignature!==JSON.stringify(cfg)} onClick={saveProfile}><Save size={16}/> บันทึกรูปแบบ</button></div>
 {preview&&<><p className="ops-preview-result">อ่าน {preview.rows} รายการ · พร้อม {preview.ready} · ต้องแก้ {preview.blocked}{previewSignature!==JSON.stringify(cfg)?' · ตั้งค่าเปลี่ยนแล้ว กรุณาดูตัวอย่างใหม่':''}</p><div className="table-scroll"><table><thead><tr><th>SKU</th><th>Qty</th><th>Price</th><th>ต้นทุน/หน่วย</th><th>ยอดขายรวม</th><th>ยอดหลังหัก</th><th>Discount</th><th>ตรวจสอบ</th></tr></thead><tbody>{preview.sample.map((r,i)=><tr key={i}><td>{r.sku}</td><td>{r.qty}</td><td>{r.price}</td><td>{num(r.source_cost_price)}</td><td>{r.gross}</td><td>{num(r.net)}</td><td>{r.discount}</td><td>{r.errors.join(' · ')||'ผ่าน'}</td></tr>)}</tbody></table></div></>}
 </section>}
 {section==='valuation'&&<section><h3>ฐานราคาและ VAT ต่อแหล่งข้อมูล</h3><p className="ops-note">ใช้เปรียบเทียบราคาขายกับต้นทุนในฐานไม่รวม VAT เมื่อระบุฐานครบ ไม่เปลี่ยนราคาต้นทางหรือราคาใน Excel · อัตราด้านล่างเป็นค่าที่คุณต้องตรวจยืนยัน</p><div className="ops-grid"><label>ลูกค้า / Shop<input aria-label="ลูกค้าฐานราคา" list="valuation-customers" value={customer} onChange={e=>{setCustomer(e.target.value);const found=savedValuations.find(v=>v.customer===e.target.value);setValuation(found?.settings||defaultValuation);}}/><datalist id="valuation-customers">{Array.from(new Set([...(batch?.groups.map(g=>g.customer)||[]),...savedValuations.map(v=>v.customer),...profiles.map(p=>p.config.customer)])).filter(Boolean).map(v=><option key={v} value={v}/>)}</datalist></label>{([['sale_basis','ราคาขาย'],['cost_basis','ต้นทุน'],['settlement_basis','ยอดหลังหัก / ส่งคืน']] as const).map(([key,label])=><label key={key}>ฐาน {label}<select aria-label={`ฐาน ${key}`} value={valuation[key]} onChange={e=>setValuation({...valuation,[key]:e.target.value as Basis})}><option value="unknown">ยังไม่ทราบ</option><option value="included">รวม VAT</option><option value="excluded">ไม่รวม VAT</option></select></label>)}<label>อัตรา VAT (%)<input aria-label="อัตรา VAT" inputMode="decimal" value={valuation.vat_rate} onChange={e=>setValuation({...valuation,vat_rate:e.target.value})}/></label><label>หมายเหตุ / ที่มายืนยัน<input aria-label="หมายเหตุฐานราคา" value={valuation.note} onChange={e=>setValuation({...valuation,note:e.target.value})}/></label></div><label className="checkbox"><input type="checkbox" disabled={!batch} checked={applyCurrent} onChange={e=>setApplyCurrent(e.target.checked)}/> ใช้กับรายการของลูกค้านี้ในชุดที่เปิดอยู่ด้วย</label><p className="ops-note">หากไม่ติ๊ก จะใช้กับการนำเข้าครั้งถัดไปเท่านั้น · การเปลี่ยนฐานในรายการเดิมอาจทำให้ต้องยืนยันขายต่ำกว่าต้นทุนใหม่</p><button className="button primary" disabled={!customer.trim()} onClick={saveValuation}>บันทึกฐานราคา</button><div className="ops-saved-settings">{savedValuations.map(v=><button className="text-button" key={v.customer} onClick={()=>{setCustomer(v.customer);setValuation(v.settings);}}>{v.customer} · VAT {v.settings.vat_rate}%</button>)}</div></section>}
 {section==='history'&&<section><button className="button secondary" disabled={!!busy||(!imports.length&&!exports.length)} onClick={clearHistory}>ล้างประวัติ Import / Export</button><p className="ops-note">ล้างทุกชุดข้อมูล · คงรายการขายและไฟล์ไว้ แต่ดาวน์โหลดผ่านประวัติที่ล้างไม่ได้ · ไฟล์ Export เดิมอยู่ใน data/local/exports (หรือโฟลเดอร์ข้อมูลที่ตั้งค่าไว้) · ประวัติใน Backup เดิมยังอยู่</p><h3>ประวัติสร้างไฟล์ Export</h3><p className="ops-note">บันทึกการสร้างไฟล์บนระบบ ไม่ได้หมายถึงส่งเข้าระบบปลายทางแล้ว · ตรวจซ้ำจากเนื้อหาและงวด ไม่ใช่ชื่อไฟล์ · เรียงรายการล่าสุดก่อน</p><div className="table-scroll"><table><thead><tr><th>เวลา / งวด</th><th>ไฟล์</th><th>SKU / รายการ</th><th>ซ้ำเนื้อหาเดิม</th><th>ไฟล์ที่บันทึกไว้</th></tr></thead><tbody>{exports.map(e=><tr key={e.id}><td>{date(e.at)}<small>{e.snapshot.period}</small></td><td>{e.filename}<small>{e.scope==='ready'?'เฉพาะที่พร้อม':'ทั้งหมด'} · ข้าม {e.skipped_rows} รายการ</small></td><td>{e.rows} SKU / {e.source_rows} รายการ</td><td>{e.previous_identical_exports?`เคยสร้างแล้ว ${e.previous_identical_exports} ครั้ง`:'ครั้งแรก'}</td><td><a className="text-button" href={`/api/export-history/${e.id}/file`}><Download size={15}/> ดาวน์โหลด</a></td></tr>)}</tbody></table></div><HistoryPagination label="Export" pager={exportPager} busy={!!busy} onChange={(page,size)=>changeHistoryPage('export',page,size)}/>{!exports.length&&<p className="ops-note">ยังไม่มีประวัติ Export</p>}<h3 className="ops-subheading">ทะเบียนไฟล์นำเข้า</h3><p className="ops-note">เก็บทะเบียนไว้ตรวจไฟล์ซ้ำแม้ล้างชุดนำเข้าแล้ว · เรียงรายการล่าสุดก่อน</p><div className="table-scroll"><table><thead><tr><th>เวลา</th><th>ไฟล์ / งวด</th><th>ผล</th><th>นำเข้าซ้ำที่ยืนยัน</th></tr></thead><tbody>{imports.map(i=><tr key={i.id}><td>{date(i.at)}</td><td>{i.name}<small>{i.period}</small></td><td>{i.error||'อ่านแล้ว'}{!i.source_available&&<small>ไฟล์ Import ถูกล้างหรือไม่พร้อมดาวน์โหลด</small>}</td><td>{i.duplicate_override?'ยืนยันนำเข้าซ้ำ':'—'}</td></tr>)}</tbody></table></div><HistoryPagination label="Import" pager={importPager} busy={!!busy} onChange={(page,size)=>changeHistoryPage('import',page,size)}/>{!imports.length&&<p className="ops-note">ยังไม่มีประวัติ Import</p>}</section>}
 {section==='backup'&&<section><h3>สำรองข้อมูลทั้งระบบ</h3><p className="ops-note">รวมชุดนำเข้า ไฟล์สำเนา Mapping กติกา รูปแบบนำเข้า ฐานราคา ประวัติยืนยัน และ Import/Export เป็น ZIP · ไม่รวมไฟล์ต้นฉบับในโฟลเดอร์หลักหรือไฟล์สำรองเก่า</p><button className="button primary" onClick={()=>run(async()=>{const result=await api<{name:string;summary:BackupSummary}>('/backups',{method:'POST'});setBackups(await api('/backups'));download(result.name);setMessage({error:false,text:`สำรองแล้ว ${result.summary.batches} ชุด / ${result.summary.rows} รายการ`});},'กำลังสร้างไฟล์สำรอง…')}><Download size={16}/> สร้างและดาวน์โหลดไฟล์สำรอง</button><h3 className="ops-subheading">กู้คืนจากไฟล์สำรอง</h3><p className="ops-note">กู้คืนแบบแทนที่ข้อมูลทั้งหมด ตรวจจำนวนรายการด้านล่างก่อนยืนยัน ระบบจะสำรองข้อมูลปัจจุบันอัตโนมัติก่อนกู้คืน · ZIP สูงสุด 250 MB</p><input ref={backupInput} hidden type="file" accept=".zip" aria-label="ไฟล์สำรองสำหรับกู้คืน" onChange={e=>{if(e.target.files?.[0])checkBackup(e.target.files[0]);}}/><button className="button secondary" onClick={()=>backupInput.current?.click()}><Upload size={16}/> เลือกไฟล์สำรองเพื่อตรวจสอบ</button>{backupPreview&&<div className="backup-preview"><h4>{backupFile?.name}</h4><p>สร้างเมื่อ {date(backupPreview.summary.created)}</p><p>{backupPreview.summary.batches} ชุด · {backupPreview.summary.rows} รายการ · {backupPreview.summary.files} ไฟล์</p><p>{backupPreview.summary.profiles} รูปแบบ · {backupPreview.summary.valuations} ฐานราคา · {backupPreview.summary.mappings} Mapping · {backupPreview.summary.rules} กติกา · {backupPreview.summary.exports} ประวัติ Export · {backupPreview.summary.imports} ประวัติ Import</p><label className="checkbox"><input type="checkbox" aria-label="ยืนยันแทนที่ข้อมูลจากสำรอง" checked={restoreConfirmed} onChange={e=>setRestoreConfirmed(e.target.checked)}/> ตรวจแล้ว ต้องการแทนที่ข้อมูลทั้งหมดด้วยไฟล์นี้</label><button className="button primary" disabled={!restoreConfirmed} onClick={restore}>กู้คืนข้อมูลที่ตรวจแล้ว</button></div>}{safetyBackup&&<p className="ops-note"><a className="text-button" href={'/api/backups/file/'+safetyBackup}>ดาวน์โหลดสำรองก่อนกู้คืนครั้งล่าสุด</a></p>}<h3 className="ops-subheading">ไฟล์สำรองที่เก็บในเครื่อง</h3><div className="backup-list">{backups.map(b=><a key={b.name} href={'/api/backups/file/'+b.name}>{b.name.startsWith('before-restore')?'ก่อนกู้คืน':'สำรองด้วยผู้ใช้'} · {b.name} · {num(b.bytes/1024)} KB <Download size={14}/></a>)}</div></section>}
 </fieldset></div>;
}


function HistoryPagination({label,pager,busy,onChange}:{label:string;pager:Pager;busy:boolean;onChange:(page:number,size:number)=>void}){
 const {page,size,total,pages}=pager;
 return <nav className="pagination history-pagination" aria-label={`แบ่งหน้าประวัติ ${label}`}>
  <span>{total?(page-1)*size+1:0}–{Math.min(page*size,total)} จาก {total.toLocaleString('th-TH')} รายการ</span>
  <div><label>ต่อหน้า <select aria-label={`จำนวนประวัติ ${label} ต่อหน้า`} disabled={busy} value={size} onChange={e=>onChange(1,Number(e.target.value))}>{[20,50,100].map(n=><option key={n} value={n}>{n}</option>)}</select></label>
  <button aria-label={`ประวัติ ${label} หน้าก่อน`} disabled={busy||page<=1} onClick={()=>onChange(page-1,size)}>ก่อนหน้า</button>
  <span>หน้า {page} / {pages}</span>
  <button aria-label={`ประวัติ ${label} หน้าถัดไป`} disabled={busy||page>=pages} onClick={()=>onChange(page+1,size)}>ถัดไป</button></div>
 </nav>;
}
