import {test,expect} from '../../frontend/node_modules/@playwright/test';
import {execFileSync} from 'node:child_process';

test('safe profile → explicit sheets → fallback Master preview → header drift rejected',async({page,request})=>{
 await request.delete('/api/batches');
 const source=execFileSync('.venv/bin/python',['-c',"import openpyxl,io,sys;w=openpyxl.Workbook();s=w.active;s.title='Sales';s.append(['Reference','Qty','Price','Cost']);s.append(['REF-1',2,100,60]);s=w.create_sheet('Branch2');s.append(['Reference','Qty','Price','Cost']);s.append(['REF-2',2,100,60]);w.create_sheet('Summary')['A1']='Summary';b=io.BytesIO();w.save(b);sys.stdout.buffer.write(b.getvalue())"]);
 const file={name:'safe-multi.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:source};
 await page.goto('/');await page.getByRole('button',{name:'ตั้งค่า / ประวัติ',exact:true}).click();
 await page.getByLabel('ชื่อรูปแบบนำเข้า').fill('Safe multi');
 await page.getByLabel('ไฟล์ตัวอย่างรูปแบบใหม่').setInputFiles(file);
 await page.getByRole('button',{name:'อ่านชีตและหัวตาราง',exact:true}).click();
 for(const [field,col] of Object.entries({partner:'A',qty:'B',price:'C',cost_price:'D'}))await page.getByLabel('คอลัมน์ '+field,{exact:true}).selectOption(col);
 await page.getByLabel('ลูกค้ารูปแบบใหม่').fill('Safe Shop');
 await page.getByRole('button',{name:'ดูตัวอย่าง Mapping',exact:true}).click();
 await expect(page.locator('.operations-panel tbody tr').last()).toContainText('0%');
 await page.getByLabel('แหล่งยอดสุทธิรูปแบบใหม่').selectOption('cost');
 await page.getByRole('button',{name:'ดูตัวอย่าง Mapping',exact:true}).click();
 await expect(page.locator('.operations-panel tbody tr').last()).toContainText('40%');
 await page.getByLabel('แหล่งยอดสุทธิรูปแบบใหม่').selectOption('mapped');
 await page.getByRole('button',{name:'ดูตัวอย่าง Mapping',exact:true}).click();
 await expect(page.locator('.operations-panel tbody tr').last()).toContainText('0%');
 await page.getByRole('button',{name:'บันทึกรูปแบบ',exact:true}).click();
 await expect(page.locator('.operations-panel [role=status]')).toContainText('บันทึกรูปแบบ Safe multi');
 const profiles=await (await request.get('/api/profiles')).json();const profile=profiles.find((p:{config:{name:string}})=>p.config.name==='Safe multi');
 expect(profile.config.expected_headers.B).toBe('Qty');
 await page.getByLabel('รูปแบบสำหรับ Import').selectOption(profile.id);
 await page.getByLabel('อัปโหลดรายงาน').setInputFiles(file);
 await expect(page.getByRole('dialog',{name:'เลือกชีตที่จะนำเข้า'})).toBeVisible();
 await page.getByRole('button',{name:'ยกเลิกการเลือกชีต'}).click();
 await expect(page.locator('.main-content>.notice')).toContainText('ยกเลิกการนำเข้าแล้ว');
 await page.getByLabel('อัปโหลดรายงาน').setInputFiles(file);
 await expect(page.getByRole('button',{name:'ยืนยันชีตและนำเข้า'})).toBeDisabled();
 await page.getByLabel('นำเข้าชีต Sales ของ safe-multi.xlsx',{exact:true}).check();
 await page.getByLabel('นำเข้าชีต Branch2 ของ safe-multi.xlsx',{exact:true}).check();
 await expect(page.getByLabel('นำเข้าชีต Summary ของ safe-multi.xlsx',{exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'ยืนยันชีตและนำเข้า'}).click();
 await expect(page.locator('.stat').filter({hasText:'รายการขาย'}).locator('strong')).toContainText('2');
 await page.getByText('ตรวจผลนำเข้าแยกตามชีต',{exact:true}).click();
 await expect(page.locator('.sheet-report')).toContainText('Branch2 · นำเข้า 1 รายการ');
 await expect(page.locator('.sheet-report')).toContainText('Summary · ข้าม');
 await page.getByRole('button',{name:'Mapping',exact:true}).click();
 const master={name:'safe-master.csv',mimeType:'text/csv',buffer:Buffer.from('Customer,PartnerCode,SKU\nSafe Shop,REF-1,REAL-1\n')};
 page.once('dialog',d=>d.dismiss());await page.getByLabel('อัปโหลดตารางอ้างอิง').setInputFiles(master);
 await expect(page.locator('.main-content>.notice')).toContainText('ยกเลิก Mapping แล้ว');
 page.once('dialog',d=>{expect(d.message()).toContain('REF-1 → REAL-1');return d.accept();});
 await page.getByLabel('อัปโหลดตารางอ้างอิง').setInputFiles(master);
 await expect(page.locator('.main-content>.notice')).toContainText('จับคู่เพิ่ม 1 รายการ');
 const batches=await (await request.get('/api/batches')).json();const url='/api/batches/'+batches[0].id;
 const rows=await (await request.get(url+'/rows')).json();expect(rows.rows.map((r:{sku:string})=>r.sku)).toContain('REAL-1');
 const changed=execFileSync('.venv/bin/python',['-c',"import openpyxl,io,sys;w=openpyxl.Workbook();s=w.active;s.title='Sales';s.append(['Reference','Price','Qty','Cost']);s.append(['REF-3',100,2,60]);b=io.BytesIO();w.save(b);sys.stdout.buffer.write(b.getvalue())"]);
 await page.getByLabel('อัปโหลดรายงาน').setInputFiles({...file,name:'changed.xlsx',buffer:changed});
 await expect(page.locator('.file-error-detail')).toContainText('หัวคอลัมน์');
 expect((await (await request.get(url)).json()).rows).toBe(2);
 await request.delete('/api/batches');await request.delete('/api/history?confirm=true');
});
