import {test,expect} from '../../frontend/node_modules/@playwright/test';
import path from 'node:path';
import fs from 'node:fs';

test('real files → review → reverse discount → master mapping → exact Excel download',async({page,request})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'รวมข้อมูลขาย ให้พร้อมใช้งาน.'})).toBeVisible();
  await expect(page.getByRole('button',{name:'Export Excel',exact:true})).toBeDisabled();
  await page.screenshot({path:'_wrx-output/evidence/demo-empty.png',fullPage:true});
  await page.getByLabel('อัปโหลดรายงาน').setInputFiles(path.resolve('data/local/samples/SALES WIX AUG 26.xlsx'));
  await expect(page.locator('.stat').filter({hasText:'รายการขาย'}).locator('strong')).toContainText('43');
  await expect(page.getByRole('button',{name:'Export Excel',exact:true})).toBeEnabled();
  await expect(page.getByRole('status')).toContainText('นำเข้าสำเร็จ 1 ไฟล์ · 43 รายการ');
  // All-source sample uses a fresh batch, avoiding duplicate King Power data.
  await page.getByRole('button',{name:'ชุดข้อมูลใหม่',exact:true}).click();
  await expect(page.locator('.stat').filter({hasText:'รายการขาย'}).locator('strong')).toContainText('0');
  let releaseImport!:()=>void;const importGate=new Promise<void>(resolve=>{releaseImport=resolve;});
  await page.route('**/api/batches/*/sample',async route=>{await importGate;await route.continue();});
  await page.getByRole('button',{name:'โหลดชุดตัวอย่าง'}).click();
  await expect(page.getByRole('dialog',{name:'กำลังดำเนินการ'})).toBeVisible();
  await expect(page.getByRole('dialog',{name:'กำลังดำเนินการ'})).toContainText('กรุณารอสักครู่');
  await page.screenshot({path:'_wrx-output/evidence/import-loading.png',fullPage:true});
  releaseImport();

  await expect(page.locator('.stat').filter({hasText:'รายการขาย'}).locator('strong')).toContainText('3,896');
  await expect(page.locator('.stat.amber strong')).toContainText('0');
  await expect(page.getByRole('button',{name:'Export Excel',exact:true})).toBeEnabled();
  await expect(page.getByRole('button',{name:'Export เฉพาะรายการที่พร้อม',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'ตรวจยอด',exact:true}).click();
  await expect(page.locator('.shop-total')).toHaveCount(5);
  await page.getByRole('button',{name:'Outlet G624',exact:true}).click();
  await expect(page.locator('.branch-total')).toHaveCount(6);
  await expect(page.locator('.shop-total').filter({hasText:'Outlet G624'})).toContainText('32,196.00');
  await expect(page.locator('.shop-total').filter({hasText:'Outlet G624'})).toContainText('ค่าเริ่มต้น 0%: 70 รายการ');
  await page.screenshot({path:'_wrx-output/evidence/shop-branch-totals.png',fullPage:true});
  await page.getByRole('button',{name:'ดูรายการ Outlet G624 ระยอง',exact:true}).click();
  await expect(page.getByLabel('กรองลูกค้า')).toHaveValue('Outlet G624');
  await expect(page.getByLabel('กรองสาขา')).toHaveValue('name:ระยอง');
  await expect(page.locator('tbody tr').first()).toContainText('ระยอง');
  const branchHistory=await (await request.get('/api/batches')).json();
  const rayong=await (await request.get(`/api/batches/${branchHistory[0].id}/rows?customer=Outlet%20G624&branch_key=name%3A${encodeURIComponent('ระยอง')}`)).json();
  await expect(page.locator('tbody tr')).toHaveCount(rayong.total);
  for(const r of await page.locator('tbody tr').all())await expect(r).toContainText('ระยอง');
  await page.getByLabel('กรองลูกค้า').selectOption('');
  await expect(page.getByLabel('กรองสาขา')).toHaveValue('');
  await expect(page.locator('tbody tr')).toHaveCount(30);
  await page.getByRole('button',{name:/^ต่ำกว่าต้นทุน/}).click();
  await expect(page.locator('.below-cost-report .merged-totals')).toContainText('17 รายการ');
  await page.locator('.below-cost-report tbody tr').first().getByRole('button',{name:'ดูรายการ'}).click();
  await expect(page.getByLabel('กรองขายต่ำกว่าต้นทุน')).toHaveValue('all');
  await expect(page.locator('tbody tr').first()).toContainText('รอตรวจสอบ');
  await page.locator('tbody tr').first().locator('.row-edit').click();
  await expect(page.locator('.below-cost-review')).toContainText('ขายต่ำกว่าต้นทุน — รอตรวจสอบ');
  await page.getByLabel('ผู้ยืนยันราคาต่ำกว่าต้นทุน').fill('E2E Sales (test only)');
  await page.getByLabel('เหตุผลราคาต่ำกว่าต้นทุน').fill('Test clearance confirmation');
  await page.getByLabel('ฐาน VAT ที่ยืนยัน').fill('ยังไม่ยืนยันว่าเป็นฐานเดียวกัน');
  await page.getByLabel('หลักฐานยืนยันราคา').fill('Isolated browser test');
  await page.getByRole('button',{name:'ยืนยันข้อมูลขายต่ำกว่าต้นทุน',exact:true}).click();
  await expect(page.locator('.below-cost-review h3')).toContainText('ยืนยันแล้ว');
  await expect(page.locator('.confirmed-info')).toContainText('ยังไม่ยืนยันว่าเทียบฐานเดียวกัน');
  await expect(page.getByRole('button',{name:'ปิดรายการ',exact:true})).toBeEnabled();
  await page.screenshot({path:'_wrx-output/evidence/below-cost-confirmed.png',fullPage:true});
  await page.getByRole('button',{name:'ปิดรายการ',exact:true}).click();
  await page.getByRole('button',{name:/^ต่ำกว่าต้นทุน/}).click();
  await expect(page.locator('.below-cost-report .merged-totals')).toContainText('รอตรวจสอบ16');
  await expect(page.locator('.below-cost-report .merged-totals')).toContainText('ยืนยันแล้ว1');
  await page.screenshot({path:'_wrx-output/evidence/below-cost-report.png',fullPage:true});
  await page.getByRole('button',{name:/^รายการขาย/}).click();
  await page.getByLabel('กรองขายต่ำกว่าต้นทุน').selectOption('');
  await page.getByLabel('กรองลูกค้า').selectOption('');
  await expect(page.locator('tbody tr')).toHaveCount(30);
  const readyDownload=page.waitForEvent('download');
  let releaseExport!:()=>void;const exportGate=new Promise<void>(resolve=>{releaseExport=resolve;});
  await page.route('**/api/batches/*/export?scope=ready',async route=>{await exportGate;await route.continue();});
  await page.getByRole('button',{name:'Export เฉพาะรายการที่พร้อม',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'กำลังดำเนินการ'})).toContainText('กำลังตรวจยอดและสร้าง Excel');
  await page.screenshot({path:'_wrx-output/evidence/export-loading.png',fullPage:true});
  releaseExport();

  const readyFile=await readyDownload;
  expect(readyFile.suggestedFilename()).toBe('Consign_2026-08_ready.xlsx');
  await readyFile.saveAs('_wrx-output/evidence/ready-only-browser-export.xlsx');
  await expect(page.getByRole('status')).toContainText('ส่งออกแล้ว 1,008 SKU จาก 3,896 รายการ · ยังไม่ส่งออก 0 รายการ');
  await expect(page.locator('.stat.amber strong')).toContainText('0');
  await expect(page.locator('tbody tr')).toHaveCount(30);
  await page.screenshot({path:'_wrx-output/evidence/demo-real-files.png',fullPage:true});
  await page.getByRole('button',{name:'รวมตาม SKU',exact:true}).click();
  await expect(page.locator('.merged-heading')).toContainText('1,008 SKU');
  await expect(page.locator('.merged-totals')).toContainText('4,795');
  await expect(page.locator('.merged-content tbody tr')).toHaveCount(30);
  await page.screenshot({path:'_wrx-output/evidence/sku-grouped-preview.png',fullPage:true});
  await page.locator('.merged-content tbody tr').first().getByRole('button').click();
  await expect(page.locator('.merged-content')).toHaveCount(0);
  await page.getByLabel('ค้นหารายการ').fill('WA-223PLACL30-EE-M');
  await expect(page.locator('tbody tr').filter({hasText:'KING POWER'})).toHaveCount(1);
  await page.getByRole('button',{name:'แก้รายการ WA-223PLACL30-EE-M',exact:true}).click();
  await expect(page.getByLabel('แก้ Discount')).toHaveValue('39.25%');
  await expect(page.locator('.calculation')).toContainText('601.40');
  await expect(page.locator('.calculation')).toContainText('1,202.80');
  await expect(page.locator('.calculation')).toContainText('1,980.00');
  await page.getByRole('button',{name:'บันทึกและตรวจยอด'}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button',{name:'แก้รายการ WA-223PLACL30-EE-M',exact:true}).click();
  await expect(page.getByLabel('แก้ Discount')).toHaveValue('39.25%');
  const discountHistory=await (await request.get('/api/batches')).json();
  const precise=await (await request.get(`/api/batches/${discountHistory[0].id}/rows?customer=KING%20POWER&sku=WA-223PLACL30-EE-M`)).json();
  expect(precise.rows[0].discount).toBe('39.2525252525%');
  expect(precise.rows[0].calculated_net).toBe('1202.8');
  // Explicitly entering the displayed rounded rate is an actual edit, unlike untouched save.
  await page.getByLabel('แก้ Discount').fill('39.24%');
  await page.getByLabel('แก้ Discount').fill('39.25%');
  await expect(page.getByLabel('แก้ยอดสุทธิ')).toHaveValue('1202.85');
  await page.getByRole('button',{name:'บันทึกและตรวจยอด'}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.locator('tbody tr').filter({hasText:'KING POWER'})).toContainText('1,202.85');
  await page.getByRole('button',{name:'แก้รายการ WA-223PLACL30-EE-M',exact:true}).click();
  await page.getByLabel('แก้ Discount').fill('39.2525252525%');
  await page.getByRole('button',{name:'บันทึกและตรวจยอด'}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button',{name:'แก้รายการ WA-223PLACL30-EE-M',exact:true}).click();

  await page.getByText('ดูข้อมูลต้นทาง',{exact:true}).click();
  await expect(page.locator('.raw-values')).toContainText('601.4');
  await page.screenshot({path:'_wrx-output/evidence/demo-reverse-discount.png',fullPage:true});
  await page.getByRole('button',{name:'ปิดรายการ',exact:true}).click();
  await page.getByLabel('ค้นหารายการ').fill('');
  await page.getByLabel('กรองสถานะ').selectOption('');
  await page.getByLabel('กรองลูกค้า').selectOption('Outlet G624');
  await expect(page.locator('tbody tr').first()).toContainText('Outlet G624');
  await page.locator('tbody tr').nth(0).getByRole('checkbox').check();
  await page.locator('tbody tr').nth(1).getByRole('checkbox').check();
  await expect(page.locator('.bulk-toolbar')).toContainText('เลือก 2 รายการ');
  await page.getByRole('button',{name:'แก้ไขรายการที่เลือก',exact:true}).click();
  await page.getByLabel('ค่าใหม่หลายรายการ').fill('0%');
  await page.getByRole('button',{name:'บันทึกให้ 2 รายการ',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('บันทึกแล้ว 2 รายการ');
  await expect(page.locator('.bulk-toolbar')).toContainText('เลือก 0 รายการ');
  await page.getByLabel('เลือกทั้งหมดในหน้านี้',{exact:true}).check();
  await expect(page.locator('tbody input:checked')).toHaveCount(30);
  await page.getByRole('button',{name:'ยกเลิกการเลือก',exact:true}).click();
  const firstRow=page.locator('tbody tr').first();
  await firstRow.locator('.row-edit').click();
  await expect(page.getByLabel('แก้ Discount')).toHaveValue('0.00%');
  await expect(page.getByRole('dialog')).toContainText('ค่าเริ่มต้น 0%');
  const p=Number(await page.getByLabel('แก้ Price').inputValue()),q=Number(await page.getByLabel('แก้ Qty').inputValue());
  await page.getByLabel('แก้ยอดสุทธิ').fill((p*q*.9).toFixed(2));
  await expect(page.getByLabel('แก้ Discount')).toHaveValue('10.00%');
  await page.getByRole('button',{name:'บันทึกและตรวจยอด'}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.locator('.stat.amber strong')).toContainText('0');
  await page.getByRole('button',{name:'Mapping',exact:true}).click();
  await page.getByLabel('ส่วนลดกลุ่ม').fill('10%');
  await page.getByRole('button',{name:'ใช้กับค่าเริ่มต้น 0%'}).click();
  await expect(page.getByRole('status')).toContainText('68 รายการ');
  await expect(page.getByRole('button',{name:'Export Excel',exact:true})).toBeEnabled();
  const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export Excel',exact:true}).click();
  const download=await downloadPromise;expect(download.suggestedFilename()).toBe('Consign_2026-08.xlsx');
  await download.saveAs('_wrx-output/evidence/e2e-synthetic-mappings-export.xlsx');
  expect(fs.statSync('_wrx-output/evidence/e2e-synthetic-mappings-export.xlsx').size).toBeGreaterThan(20000);
  await page.getByRole('button',{name:'ตรวจยอด',exact:true}).click();
  await expect(page.locator('.totals-content')).toContainText('29,284.54');
  await expect(page.locator('.shop-total').filter({hasText:'Big C'})).toContainText('1,003,055.17');
  await expect(page.locator('.shop-total').filter({hasText:'Big C'})).toContainText('802,529.70');
  await page.screenshot({path:'_wrx-output/evidence/price-cost-audit/shop-cost-totals.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'_wrx-output/evidence/demo-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  page.once('dialog',dialog=>dialog.dismiss());
  await page.getByRole('button',{name:'ล้างข้อมูลนำเข้าทั้งหมด',exact:true}).click();
  await expect(page.locator('.stat').filter({hasText:'รายการขาย'}).locator('strong')).toContainText('3,896');
  page.once('dialog',dialog=>dialog.accept());
  await page.getByRole('button',{name:'ล้างข้อมูลนำเข้าทั้งหมด',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('ล้างข้อมูลนำเข้าแล้ว');
  await expect(page.locator('.history-list button')).toHaveCount(0);
  await expect(page.getByRole('button',{name:'Export Excel',exact:true})).toBeDisabled();
  expect(await (await request.get('/api/batches')).json()).toEqual([]);
  page.once('dialog',dialog=>dialog.accept()); // Explicit re-import after clearing still checks registry.
  await page.getByLabel('อัปโหลดรายงาน').setInputFiles(path.resolve('data/local/samples/SALES WIX AUG 26.xlsx'));
  await expect(page.locator('.stat').filter({hasText:'รายการขาย'}).locator('strong')).toContainText('43');
  await expect(page.getByRole('button',{name:'Export Excel',exact:true})).toBeEnabled();
  await page.getByLabel('อัปโหลดรายงาน').setInputFiles({name:'bad.xlsx',mimeType:'application/octet-stream',buffer:Buffer.from('bad')});
  await expect(page.locator('.notice[role=alert]')).toContainText('ไฟล์ Excel ไม่สมบูรณ์');
  await expect(page.getByRole('dialog',{name:'กำลังดำเนินการ'})).toHaveCount(0);
  const current=(await (await request.get('/api/batches')).json())[0];
  const state=await (await request.get(`/api/batches/${current.id}`)).json();
  await page.route('**/api/batches/*/upload',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({...state,files:[...state.files,{id:'new-failed',name:'unknown.xlsx',kind:'ไม่รองรับ',rows:0,error:'ไม่รองรับรูปแบบนี้'},{id:'new-ok',name:'valid.xlsx',kind:'sample',rows:2,error:null}]})}));
  // This case tests the mixed-result notice, so supply an explicit successful preflight too.
  await page.route('**/api/batches/*/check-upload',route=>route.fulfill({status:200,json:[{name:'mixed.xlsx',same_batch:false,previous:[],sheets:[]}]}));
  await page.getByLabel('อัปโหลดรายงาน').setInputFiles({name:'mixed.xlsx',mimeType:'application/octet-stream',buffer:Buffer.from('mixed')});
  await expect(page.locator('.notice[role=alert]')).toContainText('นำเข้าสำเร็จบางไฟล์ · สำเร็จ 1 ไฟล์ / ไม่สำเร็จ 1 ไฟล์');
  await expect(page.getByRole('dialog',{name:'กำลังดำเนินการ'})).toHaveCount(0);
  expect(errors).toEqual([]);
});
